server {
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /usr/src/app;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;

        # Increase timeouts for FastCGI (PHP-FPM)
        fastcgi_connect_timeout 600;
        fastcgi_send_timeout 600;
        fastcgi_read_timeout 600;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /usr/src/app/public/index.php;
    }

#    location ~ \.php$ {
#        fastcgi_pass php:9000;
#        fastcgi_index index.php;
#        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
#        include fastcgi_params;
#    }
}
